### ISSUE TITLE
[REQUEST] Add TOTALTRACKS tag

### ISSUE THREAD

**Issue by cheesetosti** [unspok3n/beatportdl#54]
### Description

Would be great to have the track total automatically tagged too
I usually download 1 track from an album and then have no clue how many total tracks the album actually has. Cheers!

**Comment by unspok3n** [comment]
6919ea16bcb237b9a0b745362837341d8d972f54

**Comment by cheesetosti** [comment]
Thanks!

**Comment by SquashingBugs** [comment]
I would like to point out that some programs do not recognize "TOTALTRACKS", but rather "TRACKTOTAL" instead, like itunes for instance. There's also the case where the track and track total can be in the same tag field, like "1/4", "2/4", etc.

**Comment by cheesetosti** [comment]
You can use a simple bash script which uses metaflac to edit the tags and split "1/4" up to TRACKNUMBER=1 and TRACKTOTAL=4. Ask chatgpt to spit out a simple bash script for this and you're golden.

**Comment by SquashingBugs** [comment]
See, this is the problem. This is now adding extra steps which I already have to do with removing "CATALOGNUMBER" as I only need it in the folder structure and not track tags. Having to remove extra tags takes up extra time of mine, when it would be nice to have more config options. I'm already extremely thankful of BeatportDL existing, but some of these tag additions are now conflicting with my preferences which is why I had to create a new issue about it.

**Comment by SquashingBugs** [comment]
When I created the sub-genre suggestion for instance, I said it in a way that gives the user the choice, and not forcing it onto them.

**Comment by SquashingBugs** [comment]
My apologies. I just discovered [this](https://github.com/unspok3n/beatportdl/issues/49#issuecomment-2562646119) so I'll give it a try.
